name: k8s deployment
'on':
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
    - master
    - dev
    - release/**
    - hotfix/**
env:
  DD_DOCKER_REPO: defectdojo
  DD_HOSTNAME: defectdojo.default.minikube.local
  GITHUB_CACHE_REPO: containers.pkg.github.com
  HELM_RABBIT_BROKER_SETTINGS: ' --set redis.enabled=false --set rabbitmq.enabled=true
    --set celery.broker=rabbitmq --set createRabbitMqSecret=true '
  HELM_REDIS_BROKER_SETTINGS: ' --set redis.enabled=false --set rabbitmq.enabled=true
    --set celery.broker=rabbitmq --set createRabbitMqSecret=true '
  HELM_MYSQL_DATABASE_SETTINGS: ' --set database=mysql --set postgresql.enabled=false
    --set mysql.enabled=true --set createMysqlSecret=true '
  HELM_PG_DATABASE_SETTINGS: ' --set database=postgresql --set postgresql.enabled=true
    --set mysql.enabled=false --set createPostgresqlSecret=true '
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image:
        - django
        - nginx
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Read Docker Image Identifiers
      id: read-docker-image-identifiers
      run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]'
        '[:lower:]')" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v3
      env:
        docker-image: ${{ matrix.docker-image }}
      with:
        path: /tmp/.buildx-cache-${{ env.docker-image }}
        key: ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ github.workflow }}-${{
          github.sha }}-${{ github.run_id }}
        restore-keys: '${{ runner.os }}-buildx-${{ env.docker-image }}-${{ github.workflow
          }}-${{ github.sha }}

          ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ github.workflow }}

          ${{ runner.os }}-buildx-${{ env.docker-image }}

          '
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        docker-image: ${{ matrix.docker-image }}
      with:
        context: .
        push: false
        tags: '${{ env.DD_DOCKER_REPO }}/defectdojo-${{ env.docker-image }}:latest

          '
        file: Dockerfile.${{ env.docker-image }}
        outputs: type=docker,dest=${{ env.docker-image }}_img
        cache-from: type=local,src=/tmp/.buildx-cache-${{ env.docker-image }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.docker-image }}
    - name: Upload image ${{ env.docker-image }} as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.docker-image }}
        path: ${{ matrix.docker-image }}_img
        retention-days: 1
  setting_minikube_cluster:
    name: Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
        - databases: pgsql
          brokers: redis
          k8s: v1.18.16
        - databases: mysql
          brokers: rabbit
          k8s: v1.18.16
        - databases: pgsql
          brokers: rabbit
          k8s: v1.22.0
        - databases: mysql
          brokers: redis
          k8s: v1.22.0
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.3
      with:
        minikube version: v1.24.0
        kubernetes version: ${{ matrix.k8s }}
        driver: docker
        start args: --addons=ingress
    - name: Status of minikube
      run: minikube status
    - name: Load images from artifacts
      uses: actions/download-artifact@v3
    - name: Load docker images
      run: 'eval $(minikube docker-env)

        docker load -i nginx/nginx_img

        docker load -i django/django_img

        docker images'
    - name: Configure HELM repos
      run: 'helm repo add bitnami https://charts.bitnami.com/bitnami

        helm dependency list ./helm/defectdojo

        helm dependency update ./helm/defectdojo'
    - name: Set confings into Outputs
      id: set
      run: 'echo ::set-output name=pgsql:: "${{ env.HELM_PG_DATABASE_SETTINGS }}"

        echo ::set-output name=mysql:: "${{ env.HELM_MYSQL_DATABASE_SETTINGS }}"

        echo ::set-output name=redis:: "${{ env.HELM_REDIS_BROKER_SETTINGS }}"

        echo ::set-output name=rabbit:: "${{ env.HELM_RABBIT_BROKER_SETTINGS }}"'
    - name: Deploying Djano application with ${{ matrix.databases }} ${{ matrix.brokers
        }}
      run: "helm install \\\n  defectdojo \\\n  ./helm/defectdojo \\\n  --set django.ingress.enabled=true\
        \ \\\n  --set imagePullPolicy=Never \\\n  ${{ steps.set.outputs[matrix.databases]\
        \ }} \\\n  ${{ steps.set.outputs[matrix.brokers] }} \\\n  --set createSecret=true\
        \ \\\n  # --set imagePullSecrets=defectdojoregistrykey"
    - name: Check deployment status
      run: 'kubectl get pods

        kubectl get ingress

        kubectl get services'
    - name: Check Application
      run: "to_complete () {\n  kubectl wait --for=$1 $2 --timeout=500s --selector=$3\
        \ 2>/tmp/test || true\n  if [[ -s /tmp/test ]]; then\n    echo \"ERROR: $2\"\
        \n    cat /tmp/test\n    echo \"INFO: status:\"\n    kubectl get pods\n  \
        \  echo \"INFO: logs:\"\n    kubectl logs  --selector=$3 --all-containers=true\n\
        \    exit 1\n  fi\n  return ${?}\n}\necho \"Waiting for init job...\"\nto_complete\
        \  \"condition=Complete\" job \"defectdojo.org/component=initializer\"\necho\
        \ \"Waiting for celery pods...\"\nto_complete  \"condition=ready\" pod \"\
        defectdojo.org/component=celery\"\necho \"Waiting for django pod...\"\nto_complete\
        \  \"condition=ready\" pod \"defectdojo.org/component=django\"\necho \"Pods\
        \ up and ready to rumbole\"\nkubectl get pods\nRETRY=0\nwhile :\n  do\n  OUT=$(kubectl\
        \ run  curl --quiet=true --image=curlimages/curl:7.73.0 \\\n     --overrides='{\
        \ \"apiVersion\": \"v1\" }' \\\n     --restart=Never -i --rm -- -s -m 20 -I\
        \ --header \"Host: $DD_HOSTNAME\" http://`kubectl get service defectdojo-django\
        \ -o json \\\n    |  jq -r '.spec.clusterIP'`/login?next=/)\n  echo $OUT\n\
        \  CR=`echo $OUT | egrep \"^HTTP\" | cut -d' ' -f2`\n  echo $CR\n  if [[ $CR\
        \ -ne 200 ]]; then\n     echo $RETRY\n     if [[ $RETRY -gt 2 ]]; then\n \
        \      kubectl get pods\n       echo `kubectl logs --tail=30 -l defectdojo.org/component=django\
        \ -c uwsgi`\n       echo \"ERROR: cannot display login screen; got HTTP code\
        \ $CR\"\n       exit 1\n     else\n       ((RETRY++))\n       echo \"Attempt\
        \ $RETRY to get login page\"\n       sleep 5\n     fi\n  else\n   echo \"\
        Result received\"\n   break\n  fi\ndone\necho \"Final Check of components\"\
        \nerrors=`kubectl get pods | grep Error | awk '{print  $1}'`\nif [[ ! -z \
        \ $errors ]]; then\n  echo \"Few pods with errors\"\n  for line in $errors;\
        \ do\n    echo \"Dumping log from $line\"\n    kubectl logs --tail 50 $line\n\
        \  done\n  exit 1\nelse\n  echo \"DD K8S successfully deployed\"\nfi"
